In [9]:
import pandas as pd

In [10]:
housing_user_df = pd.read_csv('../../data/raw/nyc_user_housing_violation.csv')
housing_gov_df = pd.read_csv('../../data/raw/nyc_gov_housing_violation.csv')

In [11]:
set(housing_gov_df['currentstatus'])

{'CIV14 MAILED',
 'FALSE CERTIFICATION',
 'FIRST NO ACCESS TO RE- INSPECT VIOLATION',
 'INFO NOV SENT OUT',
 'INVALID CERTIFICATION',
 'NOT COMPLIED WITH',
 'NOTICE OF ISSUANCE SENT TO TENANT',
 'NOV CERTIFIED LATE',
 'NOV CERTIFIED ON TIME',
 'NOV SENT OUT',
 'SECOND NO ACCESS TO RE-INSPECT VIOLATION',
 'VIOLATION CLOSED',
 'VIOLATION DISMISSED',
 'VIOLATION OPEN',
 'VIOLATION WILL BE REINSPECTED'}

In [12]:
housing_user_df['buildingid'] = housing_user_df['buildingid'].astype(str)
housing_gov_df['buildingid'] = housing_gov_df['buildingid'].astype(str)

housing_user_df['apartment'] = housing_user_df['apartment'].astype(str)
housing_gov_df['apartment'] = housing_gov_df['apartment'].astype(str)

housing_user_df['location'] = housing_user_df['buildingid'] + housing_user_df['apartment']
housing_gov_df['location'] = housing_gov_df['buildingid'] + housing_gov_df['apartment']

In [15]:
housing_user_df['statusdate'] = pd.to_datetime(housing_user_df['statusdate']).dt.normalize()
housing_gov_df['currentstatusdate'] = pd.to_datetime(housing_gov_df['currentstatusdate']).dt.normalize()

In [16]:
merged_df = pd.merge(
    housing_user_df,
    housing_gov_df,
    how="inner",
    left_on=["location", "statusdate"],
    right_on=["location", "currentstatusdate"],
)

In [17]:
merged_df

,Unnamed: 0,complaintid,buildingid_x,borough,apartment_x,status,statusdate,location,violationid,buildingid_y,apartment_y,inspectiondate,approveddate,violationstatus,currentstatus,currentstatusdate
0,263,6954082,352196,BROOKLYN,14F,CLOSE,2014-07-01,35219614F,10194739,352196,14F,2014-04-02T00:00:00.000,2014-04-03T00:00:00.000,Close,VIOLATION CLOSED,2014-07-01
1,263,6954082,352196,BROOKLYN,14F,CLOSE,2014-07-01,35219614F,10194746,352196,14F,2014-04-02T00:00:00.000,2014-04-03T00:00:00.000,Close,VIOLATION CLOSED,2014-07-01
2,263,6954082,352196,BROOKLYN,14F,CLOSE,2014-07-01,35219614F,10276511,352196,14F,2014-06-12T00:00:00.000,2014-06-13T00:00:00.000,Close,VIOLATION CLOSED,2014-07-01
3,409,6932559,119270,BRONX,A9,CLOSE,2014-07-01,119270A9,10279680,119270,A9,2014-06-16T00:00:00.000,2014-06-17T00:00:00.000,Close,VIOLATION CLOSED,2014-07-01
4,562,6932554,119270,BRONX,A9,CLOSE,2014-07-01,119270A9,10279680,119270,A9,2014-06-16T00:00:00.000,2014-06-17T00:00:00.000,Close,VIOLATION CLOSED,2014-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21726,2879537,11577900,696680,QUEENS,2F,CLOSE,2022-11-28,6966802F,15318944,696680,2F,2022-04-14T00:00:00.000,2022-08-13T00:00:00.000,Close,VIOLATION DISMISSED,2022-11-28
21727,2881752,11701343,229205,BROOKLYN,B4,CLOSE,2022-11-29,229205B4,15391166,229205,B4,2022-09-23T00:00:00.000,2022-09-24T00:00:00.000,Close,VIOLATION CLOSED,2022-11-29
21728,2881752,11701343,229205,BROOKLYN,B4,CLOSE,2022-11-29,229205B4,15319716,229205,B4,2022-08-14T00:00:00.000,2022-08-17T00:00:00.000,Close,VIOLATION CLOSED,2022-11-29
21729,2881987,11667963,5635,MANHATTAN,2A,CLOSE,2022-11-30,56352A,15348232,5635,2A,2022-08-30T00:00:00.000,2022-08-30T00:00:00.000,Close,VIOLATION CLOSED,2022-11-30
21730,2882724,11755694,42496,MANHATTAN,3B,CLOSE,2022-11-30,424963B,15353942,42496,3B,2022-09-07T00:00:00.000,2022-09-11T00:00:00.000,Close,VIOLATION DISMISSED,2022-11-30

In [18]:
merged_df.to_csv('../../data/processed/aligned_housing_code.csv')